### ISSUE TITLE
TODO: version 1.0.0 (deprecated)

### ISSUE THREAD

**Issue by erming** [erming/shout#13]
This is the list of planned features for the version 1.0.0 release.
Suggestions are welcome.
- [x] Add node-webkit builds
- [x] Basic authentication
- [x] Dynamic page title
- [x] Grunt
- [ ] Join channels from GUI 
- [x] Join networks from GUI
- [ ] Keyboard shortcuts
- [x] Logging
- [x] Logo
- [x] Multiple user support
- [x] Notification sound
- [x] Plugins
- [x] Remember active window between page loads
- [x] Settings page
- [x] Theme support
- [x] Update Socket.IO to version 1.0
- [ ] Website (GitHub pages)
